/**
 * Flowtype definitions for compute
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'global' {
    declare interface Window {
        visualViewport?: {
            height: number,
            width: number
        }
    }
}
declare export type ScrollLogicalPosition = 'start' | 'center' | 'end' | 'nearest';
declare export type ScrollMode = 'always' | 'if-needed';
declare export interface Options {
    block?: ScrollLogicalPosition,
        inline?: ScrollLogicalPosition,
        scrollMode?: ScrollMode,
        boundary?: CustomScrollBoundary
}
declare export interface CustomScrollBoundaryCallback {
    (parent: Element): boolean
}
declare export type CustomScrollBoundary = Element | CustomScrollBoundaryCallback;
declare export type CustomScrollAction = {
    el: Element,
    top: number,
    left: number
};
declare var _default: (target: Element, options?: Options) => CustomScrollAction[];
declare module.exports: typeof _default