/**
 * Flowtype definitions for types
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export type ScrollBehavior = 'auto' | 'instant' | 'smooth';
declare export type ScrollLogicalPosition = 'start' | 'center' | 'end' | 'nearest';
declare export type ScrollMode = 'always' | 'if-needed';
declare export interface Options {
    block?: ScrollLogicalPosition,
        inline?: ScrollLogicalPosition,
        scrollMode?: ScrollMode,
        boundary?: CustomScrollBoundary
}
declare export interface CustomScrollBoundaryCallback {
    (parent: Element): boolean
}
declare export type CustomScrollBoundary = Element | CustomScrollBoundaryCallback;
declare export type CustomScrollAction = {
    el: Element,
    top: number,
    left: number
};